# Generated by Django 3.2.7 on 2021-09-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=1000)),
                ('about', models.TextField(max_length=1000)),
                ('experience', models.TextField(max_length=1000)),
                ('publications', models.TextField(max_length=1000)),
                ('awards', models.TextField(max_length=1000)),
                ('certifications', models.TextField(max_length=1000)),
            ],
        ),
    ]
